"""食物种子数据 - 中文常见食物"""

# 中文常见食物数据库
CHINESE_FOODS = [
    # 主食类
    {
        "name": "白米饭",
        "category": "main",
        "serving_size": 150,
        "serving_unit": "g",
        "calories_per_serving": 195,
        "carbohydrates": 43,
        "protein": 4,
        "fat": 0.5,
        "fiber": 0.5,
        "sugar": 0.5,
    },
    {
        "name": "糙米饭",
        "category": "main",
        "serving_size": 150,
        "serving_unit": "g",
        "calories_per_serving": 180,
        "carbohydrates": 38,
        "protein": 4,
        "fat": 1.5,
        "fiber": 2.5,
        "sugar": 0.5,
    },
    {
        "name": "面条",
        "category": "main",
        "serving_size": 150,
        "serving_unit": "g",
        "calories_per_serving": 220,
        "carbohydrates": 45,
        "protein": 6,
        "fat": 2,
        "fiber": 2,
        "sugar": 1,
    },
    {
        "name": "馒头",
        "category": "main",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 230,
        "carbohydrates": 48,
        "protein": 7,
        "fat": 1,
        "fiber": 1.5,
        "sugar": 1,
    },
    {
        "name": "包子",
        "category": "main",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 250,
        "carbohydrates": 35,
        "protein": 10,
        "fat": 8,
        "fiber": 1.5,
        "sugar": 1,
    },
    {
        "name": "饺子",
        "category": "main",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 240,
        "carbohydrates": 30,
        "protein": 12,
        "fat": 9,
        "fiber": 1.5,
        "sugar": 1,
    },
    {
        "name": "小米粥",
        "category": "main",
        "serving_size": 200,
        "serving_unit": "ml",
        "calories_per_serving": 120,
        "carbohydrates": 25,
        "protein": 3,
        "fat": 1,
        "fiber": 1,
        "sugar": 0.5,
    },
    {
        "name": "玉米",
        "category": "main",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 86,
        "carbohydrates": 19,
        "protein": 3,
        "fat": 1.5,
        "fiber": 2.5,
        "sugar": 4,
    },
    # 蔬菜类
    {
        "name": "炒青菜",
        "category": "vegetable",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 80,
        "carbohydrates": 6,
        "protein": 2,
        "fat": 5,
        "fiber": 2,
        "sugar": 2,
    },
    {
        "name": "西红柿炒蛋",
        "category": "vegetable",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 140,
        "carbohydrates": 6,
        "protein": 9,
        "fat": 9,
        "fiber": 1,
        "sugar": 4,
    },
    {
        "name": "麻婆豆腐",
        "category": "vegetable",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 150,
        "carbohydrates": 8,
        "protein": 10,
        "fat": 10,
        "fiber": 2,
        "sugar": 2,
    },
    {
        "name": "西兰花",
        "category": "vegetable",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 55,
        "carbohydrates": 11,
        "protein": 4,
        "fat": 0.5,
        "fiber": 5,
        "sugar": 2,
    },
    {
        "name": "炒豆芽",
        "category": "vegetable",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 90,
        "carbohydrates": 7,
        "protein": 4,
        "fat": 6,
        "fiber": 3,
        "sugar": 2,
    },
    {
        "name": "凉拌黄瓜",
        "category": "vegetable",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 60,
        "carbohydrates": 8,
        "protein": 1,
        "fat": 3,
        "fiber": 1.5,
        "sugar": 3,
    },
    # 肉类
    {
        "name": "红烧肉",
        "category": "side",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 350,
        "carbohydrates": 12,
        "protein": 18,
        "fat": 28,
        "fiber": 0.5,
        "sugar": 8,
    },
    {
        "name": "糖醋里脊",
        "category": "side",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 280,
        "carbohydrates": 25,
        "protein": 15,
        "fat": 14,
        "fiber": 0.5,
        "sugar": 12,
    },
    {
        "name": "宫保鸡丁",
        "category": "side",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 200,
        "carbohydrates": 12,
        "protein": 18,
        "fat": 10,
        "fiber": 2,
        "sugar": 6,
    },
    {
        "name": "清蒸鱼",
        "category": "side",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 120,
        "carbohydrates": 3,
        "protein": 22,
        "fat": 3,
        "fiber": 0,
        "sugar": 1,
    },
    {
        "name": "红烧排骨",
        "category": "side",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 320,
        "carbohydrates": 10,
        "protein": 20,
        "fat": 24,
        "fiber": 0.5,
        "sugar": 6,
    },
    {
        "name": "白切鸡",
        "category": "side",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 160,
        "carbohydrates": 2,
        "protein": 25,
        "fat": 6,
        "fiber": 0,
        "sugar": 0,
    },
    # 汤类
    {
        "name": "紫菜蛋花汤",
        "category": "side",
        "serving_size": 200,
        "serving_unit": "ml",
        "calories_per_serving": 80,
        "carbohydrates": 5,
        "protein": 6,
        "fat": 4,
        "fiber": 0.5,
        "sugar": 1,
    },
    {
        "name": "冬瓜排骨汤",
        "category": "side",
        "serving_size": 200,
        "serving_unit": "ml",
        "calories_per_serving": 150,
        "carbohydrates": 8,
        "protein": 10,
        "fat": 10,
        "fiber": 0.5,
        "sugar": 2,
    },
    # 零食
    {
        "name": "薯片",
        "category": "snack",
        "serving_size": 50,
        "serving_unit": "g",
        "calories_per_serving": 270,
        "carbohydrates": 28,
        "protein": 3,
        "fat": 16,
        "fiber": 1.5,
        "sugar": 1,
    },
    {
        "name": "饼干",
        "category": "snack",
        "serving_size": 30,
        "serving_unit": "g",
        "calories_per_serving": 150,
        "carbohydrates": 20,
        "protein": 2,
        "fat": 7,
        "fiber": 0.5,
        "sugar": 8,
    },
    {
        "name": "巧克力",
        "category": "snack",
        "serving_size": 30,
        "serving_unit": "g",
        "calories_per_serving": 160,
        "carbohydrates": 18,
        "protein": 2,
        "fat": 9,
        "fiber": 2,
        "sugar": 15,
    },
    {
        "name": "坚果混合",
        "category": "snack",
        "serving_size": 30,
        "serving_unit": "g",
        "calories_per_serving": 190,
        "carbohydrates": 7,
        "protein": 5,
        "fat": 16,
        "fiber": 2,
        "sugar": 2,
    },
    {
        "name": "酸奶",
        "category": "snack",
        "serving_size": 150,
        "serving_unit": "ml",
        "calories_per_serving": 100,
        "carbohydrates": 12,
        "protein": 8,
        "fat": 3,
        "fiber": 0,
        "sugar": 10,
    },
    {
        "name": "水果沙拉",
        "category": "snack",
        "serving_size": 150,
        "serving_unit": "g",
        "calories_per_serving": 80,
        "carbohydrates": 18,
        "protein": 1,
        "fat": 0.5,
        "fiber": 3,
        "sugar": 14,
    },
    # 水果
    {
        "name": "苹果",
        "category": "fruit",
        "serving_size": 150,
        "serving_unit": "g",
        "calories_per_serving": 78,
        "carbohydrates": 21,
        "protein": 0.3,
        "fat": 0.3,
        "fiber": 3.5,
        "sugar": 16,
    },
    {
        "name": "香蕉",
        "category": "fruit",
        "serving_size": 120,
        "serving_unit": "g",
        "calories_per_serving": 105,
        "carbohydrates": 27,
        "protein": 1.3,
        "fat": 0.4,
        "fiber": 3,
        "sugar": 14,
    },
    {
        "name": "橙子",
        "category": "fruit",
        "serving_size": 150,
        "serving_unit": "g",
        "calories_per_serving": 70,
        "carbohydrates": 18,
        "protein": 1.5,
        "fat": 0.2,
        "fiber": 3.5,
        "sugar": 12,
    },
    {
        "name": "葡萄",
        "category": "fruit",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 69,
        "carbohydrates": 18,
        "protein": 0.7,
        "fat": 0.2,
        "fiber": 0.9,
        "sugar": 15,
    },
    {
        "name": "西瓜",
        "category": "fruit",
        "serving_size": 200,
        "serving_unit": "g",
        "calories_per_serving": 60,
        "carbohydrates": 15,
        "protein": 1.2,
        "fat": 0.2,
        "fiber": 1,
        "sugar": 10,
    },
    {
        "name": "猕猴桃",
        "category": "fruit",
        "serving_size": 100,
        "serving_unit": "g",
        "calories_per_serving": 61,
        "carbohydrates": 15,
        "protein": 1,
        "fat": 0.5,
        "fiber": 3,
        "sugar": 9,
    },
    # 饮品
    {
        "name": "绿茶",
        "category": "drink",
        "serving_size": 250,
        "serving_unit": "ml",
        "calories_per_serving": 2,
        "carbohydrates": 0.5,
        "protein": 0,
        "fat": 0,
        "fiber": 0,
        "sugar": 0,
    },
    {
        "name": "豆浆",
        "category": "drink",
        "serving_size": 250,
        "serving_unit": "ml",
        "calories_per_serving": 100,
        "carbohydrates": 6,
        "protein": 8,
        "fat": 4,
        "fiber": 1,
        "sugar": 3,
    },
    {
        "name": "牛奶",
        "category": "drink",
        "serving_size": 250,
        "serving_unit": "ml",
        "calories_per_serving": 150,
        "carbohydrates": 12,
        "protein": 8,
        "fat": 8,
        "fiber": 0,
        "sugar": 12,
    },
    {
        "name": "可乐",
        "category": "drink",
        "serving_size": 330,
        "serving_unit": "ml",
        "calories_per_serving": 140,
        "carbohydrates": 35,
        "protein": 0,
        "fat": 0,
        "fiber": 0,
        "sugar": 35,
    },
    {
        "name": "橙汁",
        "category": "drink",
        "serving_size": 250,
        "serving_unit": "ml",
        "calories_per_serving": 110,
        "carbohydrates": 26,
        "protein": 2,
        "fat": 0.5,
        "fiber": 0.5,
        "sugar": 21,
    },
]


async def seed_foods(db) -> None:
    """初始化食物数据库"""
    from app.models import Food
    from datetime import datetime
    from sqlalchemy import select

    # 检查是否已经有数据
    result = await db.execute(select(Food).limit(1))
    if result.scalar_one_or_none() is not None:
        print("食物数据库已存在，跳过初始化")
        return

    print("开始初始化食物数据库...")

    for food_data in CHINESE_FOODS:
        food = Food(
            name=food_data["name"],
            category=food_data["category"],
            serving_size=food_data["serving_size"],
            serving_unit=food_data["serving_unit"],
            calories_per_serving=food_data["calories_per_serving"],
            carbohydrates=food_data["carbohydrates"],
            protein=food_data["protein"],
            fat=food_data["fat"],
            fiber=food_data["fiber"],
            sugar=food_data["sugar"],
            is_custom=0,
            created_at=datetime.now().isoformat(),
        )
        db.add(food)

    await db.commit()
    print(f"已初始化 {len(CHINESE_FOODS)} 种食物")


async def init_default_user(db) -> None:
    """初始化默认用户"""
    from app.models import User
    from datetime import datetime
    from sqlalchemy import select

    # 检查是否已经有默认用户
    result = await db.execute(select(User).where(User.device_id == "default"))
    if result.scalar_one_or_none() is not None:
        print("默认用户已存在，跳过初始化")
        return

    print("创建默认用户...")

    user = User(
        device_id="default",
        username="CalEE 用户",
        avatar_url=None,
        daily_calorie_goal=1200,
        created_at=datetime.now().isoformat(),
    )
    db.add(user)
    await db.commit()
    print("默认用户创建成功")
